name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  RUBY_VERSION: 3.2.6

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erblint app/{cells,views}/**/*.erb
        name: Lint ERB files

      - name: Lint JS files
        run: npm run lint:js

      - name: Lint SCSS files
        run: npm run lint:scss
