name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.2.6
      NODE_VERSION: 18.17.1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Ruby files
        run: bundle exec rubocop -P

      - name: Lint ERB files
        run: bundle exec erblint app/{cells,views}/**/*.erb

      - name: Lint JS files
        run: npm run lint

      - name: Lint SCSS files
        run: npm run stylelint

      - name: Check SCSS formatting
        run: npm run prettier
